import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'
import { QueryClientProvider, QueryClient } from '@tanstack/react-query'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const queryClient = new QueryClient()
  return (
    <html lang="en">
      <Header />
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}> {children}</QueryClientProvider>

      </body>
      <Footer />
    </html>
  )
}
